Add workingDirectory input
paambaati/codeclimate-action pull request #220
Opened 2020-09-02 02:24 UTC by arareko

GitHub action's `uses` step do not allow changing/specifying the working directory to execute the action being included. This patch add a `workingDirectory` input to allow changing to a custom working directory.

2020-09-02 03:59 UTC, arareko commented on .github/workflows/release.yml
> +          COMMIT_EMAIL: 'mauricio@arareko.net'
I'll undo this. Using temporarily to test this.

2020-09-02 04:16 UTC, arareko commented on .github/workflows/release.yml
> +          COMMIT_EMAIL: 'mauricio@arareko.net'
also temporarily adding a couple directories for testing purposes.

2020-09-09 17:31 UTC, arareko commented
Hi @paambaati, any chance you can have a look at this?

2020-09-16 05:04 UTC, arareko commented
Hi @vladjerca, @mattvv & @MartinNuc, can any of you take a look at this? Thanks!

2020-09-16 17:52 UTC, vladjerca approved these changes
Looks good to me 👍

2020-09-16 17:53 UTC, vladjerca commented
@arareko Nice addition, but it's on @paambaati to get this merged, don't know who else has merge rights on the repo 😋

2020-09-16 19:09 UTC, arareko commented
> @arareko Nice addition, but it's on @paambaati to get this merged, don't know who else has merge rights on the repo 😋

thanks for the comment! hopefully @paambaati gets to see this then..

2020-09-16 22:53 UTC, MartinNuc approved these changes
LGTM 👍

2020-09-22 06:32 UTC, paambaati commented
I'm so sorry folks, I'd been busy with work. I'm looking at this PR right now and you can expect it to be merged in the next few hours.

2020-09-22 07:14 UTC, paambaati requested changes

2020-09-22 07:14 UTC, paambaati commented on src/main.ts
> +        await chdir(workingDirectory);
```suggestion
chdir(workingDirectory);
```

You don't need to `await` this, the [`chdir()`](https://nodejs.org/api/process.html#process_process_chdir_directory) method doesn't return a promise.

2020-09-22 07:17 UTC, paambaati commented on src/main.ts
> +    if (workingDirectory) {
```suggestion
    if (workingDirectory.length) {
```

This way, this `if` block doesn't have to be executed if the working directory is the default.

2020-09-22 07:21 UTC, paambaati commented on src/main.ts
> +      error(err.message);
But now I see that I've myself done both at different places, so thanks, this will at least help standardize this.

2020-09-22 09:15 UTC, merged

2020-09-22 09:15 UTC, paambaati commented
@arareko Thanks a lot for this PR! I'll be following this up with tests.

2020-09-22 18:36 UTC, arareko commented
> @arareko Thanks a lot for this PR! I'll be following this up with tests.

@paambaati I just saw you added the tests and released this feature along with a new version. Thanks so much. Cheers!