234 - Glob support for coverage locations
paambaati/codeclimate-action pull request #240
Opened 2020-10-01 15:55 UTC by Sumolari

Now you can pass globs as coverage locations, `@actions/glob` is used to convert them to absolute paths.

Fixes #234

2020-10-01 16:00 UTC, paambaati requested changes

2020-10-01 16:01 UTC, Sumolari commented on test/main.test.ts
> +  writeFileSync(fileB, 'file a content');
Yeap, updated

2020-10-03 07:12 UTC, paambaati approved these changes

2020-10-03 07:12 UTC, merged

2020-10-03 07:31 UTC, paambaati commented
@Sumolari Thanks a lot for this PR! This has now landed in [`v2.7.4`](https://github.com/paambaati/codeclimate-action/releases/tag/v2.7.4) 🎉